package com.wlabs.parkoo.frontend;

//Custom package
import com.wlabs.parkoo.backend.database.VoitureDAO;
import com.wlabs.parkoo.backend.*;

//Java package
import java.awt.Color;
import javax.swing.JPanel;

/**
 * @licence MIT Licence
 * @author Wilfried AGO
 * @email wilfriedago@pm.me
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        this.allSpans = new JPanel[]{span1, span2, span3, span4, span5};
        this.allLinks = new JPanel[]{linkHome, linkVoiture, linkVente, linkClient, linkCaissier};
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationContainer = new javax.swing.JPanel();
        linkHome = new javax.swing.JPanel();
        span1 = new javax.swing.JPanel();
        linkHomeText = new javax.swing.JLabel();
        linkVoiture = new javax.swing.JPanel();
        span2 = new javax.swing.JPanel();
        linkVoitureText = new javax.swing.JLabel();
        linkVente = new javax.swing.JPanel();
        span3 = new javax.swing.JPanel();
        linkVenteText = new javax.swing.JLabel();
        linkClient = new javax.swing.JPanel();
        span4 = new javax.swing.JPanel();
        linkClientText = new javax.swing.JLabel();
        linkCaissier = new javax.swing.JPanel();
        span5 = new javax.swing.JPanel();
        linkCaissierText = new javax.swing.JLabel();
        statusContainer = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        separator = new javax.swing.JPanel();
        actualPanel = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        separator2 = new javax.swing.JPanel();
        separator3 = new javax.swing.JSeparator();
        searchVehiculeLabel = new javax.swing.JLabel();
        searchVehiculeField = new javax.swing.JTextField();
        searchVehiculeButton = new javax.swing.JButton();
        makeResult = new javax.swing.JButton();
        addVehicule = new javax.swing.JButton();
        mainActionContainer = new javax.swing.JPanel();
        actionVoiture = new javax.swing.JPanel();
        actionDescription = new javax.swing.JLabel();
        actionDetails = new javax.swing.JLabel();
        actionVente = new javax.swing.JPanel();
        actionDescription1 = new javax.swing.JLabel();
        actionDetails1 = new javax.swing.JLabel();
        actionClient = new javax.swing.JPanel();
        actionDescription2 = new javax.swing.JLabel();
        actionDetails2 = new javax.swing.JLabel();
        actionCaissier = new javax.swing.JPanel();
        actionDescription3 = new javax.swing.JLabel();
        actionDetails3 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        actionQuitter = new javax.swing.JMenuItem();
        menuEdition = new javax.swing.JMenu();
        menuAide = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parkoo - Cars Inventory Management");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("MainContainer"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 700));
        setSize(new java.awt.Dimension(1024, 700));

        navigationContainer.setBackground(new java.awt.Color(61, 118, 202));
        navigationContainer.setToolTipText("");
        navigationContainer.setMinimumSize(new java.awt.Dimension(150, 100));
        navigationContainer.setPreferredSize(new java.awt.Dimension(150, 700));

        linkHome.setBackground(new java.awt.Color(79, 134, 214));
        linkHome.setToolTipText("");
        linkHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkHome.setPreferredSize(new java.awt.Dimension(150, 40));
        linkHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linkHomeMousePressed(evt);
            }
        });

        span1.setBackground(new java.awt.Color(255, 255, 255));
        span1.setPreferredSize(new java.awt.Dimension(3, 40));

        javax.swing.GroupLayout span1Layout = new javax.swing.GroupLayout(span1);
        span1.setLayout(span1Layout);
        span1Layout.setHorizontalGroup(
            span1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        span1Layout.setVerticalGroup(
            span1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        linkHomeText.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        linkHomeText.setForeground(new java.awt.Color(255, 255, 255));
        linkHomeText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/home.png"))); // NOI18N
        linkHomeText.setText("Acceuil");

        javax.swing.GroupLayout linkHomeLayout = new javax.swing.GroupLayout(linkHome);
        linkHome.setLayout(linkHomeLayout);
        linkHomeLayout.setHorizontalGroup(
            linkHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkHomeLayout.createSequentialGroup()
                .addComponent(span1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkHomeText)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        linkHomeLayout.setVerticalGroup(
            linkHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkHomeLayout.createSequentialGroup()
                .addComponent(span1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(linkHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkHomeText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        linkVoiture.setBackground(new java.awt.Color(61, 118, 202));
        linkVoiture.setToolTipText("Voir la liste des voitures en stock");
        linkVoiture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkVoiture.setPreferredSize(new java.awt.Dimension(150, 40));
        linkVoiture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linkVoitureMousePressed(evt);
            }
        });

        span2.setBackground(new java.awt.Color(255, 255, 255));
        span2.setOpaque(false);
        span2.setPreferredSize(new java.awt.Dimension(3, 40));

        javax.swing.GroupLayout span2Layout = new javax.swing.GroupLayout(span2);
        span2.setLayout(span2Layout);
        span2Layout.setHorizontalGroup(
            span2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        span2Layout.setVerticalGroup(
            span2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        linkVoitureText.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        linkVoitureText.setForeground(new java.awt.Color(255, 255, 255));
        linkVoitureText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/car.png"))); // NOI18N
        linkVoitureText.setText("Voitures");

        javax.swing.GroupLayout linkVoitureLayout = new javax.swing.GroupLayout(linkVoiture);
        linkVoiture.setLayout(linkVoitureLayout);
        linkVoitureLayout.setHorizontalGroup(
            linkVoitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkVoitureLayout.createSequentialGroup()
                .addComponent(span2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(linkVoitureText)
                .addGap(45, 45, 45))
        );
        linkVoitureLayout.setVerticalGroup(
            linkVoitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkVoitureLayout.createSequentialGroup()
                .addComponent(span2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(linkVoitureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkVoitureText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        linkVente.setBackground(new java.awt.Color(61, 118, 202));
        linkVente.setToolTipText("Voir la liste de toutes les ventes effectuées");
        linkVente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkVente.setPreferredSize(new java.awt.Dimension(150, 40));
        linkVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linkVenteMousePressed(evt);
            }
        });

        span3.setBackground(new java.awt.Color(255, 255, 255));
        span3.setOpaque(false);
        span3.setPreferredSize(new java.awt.Dimension(3, 40));

        javax.swing.GroupLayout span3Layout = new javax.swing.GroupLayout(span3);
        span3.setLayout(span3Layout);
        span3Layout.setHorizontalGroup(
            span3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        span3Layout.setVerticalGroup(
            span3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        linkVenteText.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        linkVenteText.setForeground(new java.awt.Color(255, 255, 255));
        linkVenteText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/stack.png"))); // NOI18N
        linkVenteText.setText("Ventes");

        javax.swing.GroupLayout linkVenteLayout = new javax.swing.GroupLayout(linkVente);
        linkVente.setLayout(linkVenteLayout);
        linkVenteLayout.setHorizontalGroup(
            linkVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkVenteLayout.createSequentialGroup()
                .addComponent(span3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkVenteText)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        linkVenteLayout.setVerticalGroup(
            linkVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkVenteLayout.createSequentialGroup()
                .addComponent(span3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linkVenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(linkVenteText)
                .addContainerGap())
        );

        linkClient.setBackground(new java.awt.Color(61, 118, 202));
        linkClient.setToolTipText("Voir la liste des clients");
        linkClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkClient.setPreferredSize(new java.awt.Dimension(150, 40));
        linkClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linkClientMousePressed(evt);
            }
        });

        span4.setBackground(new java.awt.Color(255, 255, 255));
        span4.setOpaque(false);
        span4.setPreferredSize(new java.awt.Dimension(3, 40));

        javax.swing.GroupLayout span4Layout = new javax.swing.GroupLayout(span4);
        span4.setLayout(span4Layout);
        span4Layout.setHorizontalGroup(
            span4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        span4Layout.setVerticalGroup(
            span4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        linkClientText.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        linkClientText.setForeground(new java.awt.Color(255, 255, 255));
        linkClientText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/users.png"))); // NOI18N
        linkClientText.setText("Clients");

        javax.swing.GroupLayout linkClientLayout = new javax.swing.GroupLayout(linkClient);
        linkClient.setLayout(linkClientLayout);
        linkClientLayout.setHorizontalGroup(
            linkClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkClientLayout.createSequentialGroup()
                .addComponent(span4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkClientText)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        linkClientLayout.setVerticalGroup(
            linkClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkClientLayout.createSequentialGroup()
                .addComponent(span4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linkClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(linkClientText)
                .addContainerGap())
        );

        linkCaissier.setBackground(new java.awt.Color(61, 118, 202));
        linkCaissier.setToolTipText("Voir la liste des caissiers");
        linkCaissier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkCaissier.setPreferredSize(new java.awt.Dimension(150, 40));
        linkCaissier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linkCaissierMousePressed(evt);
            }
        });

        span5.setBackground(new java.awt.Color(255, 255, 255));
        span5.setOpaque(false);
        span5.setPreferredSize(new java.awt.Dimension(3, 40));

        javax.swing.GroupLayout span5Layout = new javax.swing.GroupLayout(span5);
        span5.setLayout(span5Layout);
        span5Layout.setHorizontalGroup(
            span5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        span5Layout.setVerticalGroup(
            span5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        linkCaissierText.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        linkCaissierText.setForeground(new java.awt.Color(255, 255, 255));
        linkCaissierText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/user-check.png"))); // NOI18N
        linkCaissierText.setText("Caissiers");

        javax.swing.GroupLayout linkCaissierLayout = new javax.swing.GroupLayout(linkCaissier);
        linkCaissier.setLayout(linkCaissierLayout);
        linkCaissierLayout.setHorizontalGroup(
            linkCaissierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkCaissierLayout.createSequentialGroup()
                .addComponent(span5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkCaissierText)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        linkCaissierLayout.setVerticalGroup(
            linkCaissierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkCaissierLayout.createSequentialGroup()
                .addComponent(span5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(linkCaissierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkCaissierText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navigationContainerLayout = new javax.swing.GroupLayout(navigationContainer);
        navigationContainer.setLayout(navigationContainerLayout);
        navigationContainerLayout.setHorizontalGroup(
            navigationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linkHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(linkVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(linkVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(linkClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(linkCaissier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        navigationContainerLayout.setVerticalGroup(
            navigationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationContainerLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(linkHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linkVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linkVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linkClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linkCaissier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        statusContainer.setBackground(new java.awt.Color(255, 255, 255));
        statusContainer.setPreferredSize(new java.awt.Dimension(753, 60));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/logo.png"))); // NOI18N

        separator.setBackground(new java.awt.Color(240, 240, 240));
        separator.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout separatorLayout = new javax.swing.GroupLayout(separator);
        separator.setLayout(separatorLayout);
        separatorLayout.setHorizontalGroup(
            separatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        separatorLayout.setVerticalGroup(
            separatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        actualPanel.setBackground(new java.awt.Color(49, 49, 49));
        actualPanel.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        actualPanel.setForeground(new java.awt.Color(49, 49, 49));
        actualPanel.setText("Acceuil");

        javax.swing.GroupLayout statusContainerLayout = new javax.swing.GroupLayout(statusContainer);
        statusContainer.setLayout(statusContainerLayout);
        statusContainerLayout.setHorizontalGroup(
            statusContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusContainerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(logo)
                .addGap(34, 34, 34)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(actualPanel))
        );
        statusContainerLayout.setVerticalGroup(
            statusContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusContainerLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(logo))
            .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(statusContainerLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(actualPanel))
        );

        mainContainer.setBackground(new java.awt.Color(244, 245, 247));
        mainContainer.setForeground(new java.awt.Color(244, 245, 247));

        separator2.setBackground(new java.awt.Color(240, 240, 240));
        separator2.setPreferredSize(new java.awt.Dimension(800, 2));

        javax.swing.GroupLayout separator2Layout = new javax.swing.GroupLayout(separator2);
        separator2.setLayout(separator2Layout);
        separator2Layout.setHorizontalGroup(
            separator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        separator2Layout.setVerticalGroup(
            separator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        separator3.setBackground(new java.awt.Color(240, 240, 240));
        separator3.setForeground(new java.awt.Color(187, 187, 187));

        searchVehiculeLabel.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        searchVehiculeLabel.setForeground(new java.awt.Color(129, 138, 148));
        searchVehiculeLabel.setText("Rechercher un vehicule");

        searchVehiculeField.setBackground(new java.awt.Color(255, 255, 255));
        searchVehiculeField.setFont(new java.awt.Font("Dubai", 0, 15)); // NOI18N
        searchVehiculeField.setForeground(new java.awt.Color(129, 138, 148));
        searchVehiculeField.setToolTipText("Rechercher un vehicule grace à son numéro de série");
        searchVehiculeField.setName("Rechercher un vehicule"); // NOI18N
        searchVehiculeField.setPreferredSize(new java.awt.Dimension(190, 35));

        searchVehiculeButton.setBackground(new java.awt.Color(61, 118, 202));
        searchVehiculeButton.setForeground(new java.awt.Color(255, 255, 255));
        searchVehiculeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/search.png"))); // NOI18N
        searchVehiculeButton.setToolTipText("Rechercher un vehicule grace à son numéro de série");
        searchVehiculeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 118, 202), 1, true));
        searchVehiculeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchVehiculeButton.setPreferredSize(new java.awt.Dimension(35, 35));
        searchVehiculeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVehiculeButtonActionPerformed(evt);
            }
        });

        makeResult.setBackground(new java.awt.Color(255, 255, 255));
        makeResult.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        makeResult.setForeground(new java.awt.Color(61, 118, 202));
        makeResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/result.png"))); // NOI18N
        makeResult.setText("Faire le bilan");
        makeResult.setToolTipText("Effectuer le bilan, et visualiser les bénéfices");
        makeResult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 118, 202), 1, true));
        makeResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        makeResult.setIconTextGap(5);
        makeResult.setMargin(new java.awt.Insets(4, 10, 4, 16));
        makeResult.setName(""); // NOI18N
        makeResult.setPreferredSize(new java.awt.Dimension(150, 35));
        makeResult.setRequestFocusEnabled(false);
        makeResult.setVerifyInputWhenFocusTarget(false);

        addVehicule.setBackground(new java.awt.Color(61, 118, 202));
        addVehicule.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        addVehicule.setForeground(new java.awt.Color(255, 255, 255));
        addVehicule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wlabs/parkoo/frontend/assets/icons/plus.png"))); // NOI18N
        addVehicule.setText("Enregistrer un vehicule");
        addVehicule.setToolTipText("Enregistrer un nouveau véhicule dans la BDD");
        addVehicule.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 118, 202), 1, true));
        addVehicule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addVehicule.setIconTextGap(5);
        addVehicule.setMargin(new java.awt.Insets(4, 10, 4, 16));
        addVehicule.setName(""); // NOI18N
        addVehicule.setPreferredSize(new java.awt.Dimension(190, 35));
        addVehicule.setRequestFocusEnabled(false);
        addVehicule.setVerifyInputWhenFocusTarget(false);
        addVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addVehiculeMousePressed(evt);
            }
        });

        mainActionContainer.setBackground(new java.awt.Color(244, 245, 247));
        mainActionContainer.setForeground(new java.awt.Color(244, 245, 247));

        actionVoiture.setBackground(new java.awt.Color(250, 253, 255));
        actionVoiture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 206, 255), 1, true));
        actionVoiture.setForeground(new java.awt.Color(164, 206, 255));
        actionVoiture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actionVoiture.setPreferredSize(new java.awt.Dimension(180, 130));

        actionDescription.setBackground(new java.awt.Color(255, 255, 255));
        actionDescription.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        actionDescription.setForeground(new java.awt.Color(118, 130, 142));
        actionDescription.setText("Voitures");

        actionDetails.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        actionDetails.setForeground(new java.awt.Color(118, 130, 142));
        actionDetails.setText("202 Voiture(s) en stock");

        javax.swing.GroupLayout actionVoitureLayout = new javax.swing.GroupLayout(actionVoiture);
        actionVoiture.setLayout(actionVoitureLayout);
        actionVoitureLayout.setHorizontalGroup(
            actionVoitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionVoitureLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(actionVoitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionDetails)
                    .addComponent(actionDescription))
                .addContainerGap())
        );
        actionVoitureLayout.setVerticalGroup(
            actionVoitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionVoitureLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(actionDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(actionDetails)
                .addContainerGap())
        );

        actionVente.setBackground(new java.awt.Color(250, 253, 255));
        actionVente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 206, 255), 1, true));
        actionVente.setForeground(new java.awt.Color(164, 206, 255));
        actionVente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actionVente.setPreferredSize(new java.awt.Dimension(180, 130));

        actionDescription1.setBackground(new java.awt.Color(255, 255, 255));
        actionDescription1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        actionDescription1.setForeground(new java.awt.Color(118, 130, 142));
        actionDescription1.setText("Ventes");

        actionDetails1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        actionDetails1.setForeground(new java.awt.Color(118, 130, 142));
        actionDetails1.setText("22 Vente(s) effectuées");

        javax.swing.GroupLayout actionVenteLayout = new javax.swing.GroupLayout(actionVente);
        actionVente.setLayout(actionVenteLayout);
        actionVenteLayout.setHorizontalGroup(
            actionVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionVenteLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(actionVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionDetails1)
                    .addComponent(actionDescription1))
                .addContainerGap())
        );
        actionVenteLayout.setVerticalGroup(
            actionVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionVenteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(actionDescription1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(actionDetails1)
                .addContainerGap())
        );

        actionClient.setBackground(new java.awt.Color(250, 253, 255));
        actionClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 206, 255), 1, true));
        actionClient.setForeground(new java.awt.Color(164, 206, 255));
        actionClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actionClient.setPreferredSize(new java.awt.Dimension(180, 130));

        actionDescription2.setBackground(new java.awt.Color(255, 255, 255));
        actionDescription2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        actionDescription2.setForeground(new java.awt.Color(118, 130, 142));
        actionDescription2.setText("Clients");

        actionDetails2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        actionDetails2.setForeground(new java.awt.Color(118, 130, 142));
        actionDetails2.setText("20 Clients");

        javax.swing.GroupLayout actionClientLayout = new javax.swing.GroupLayout(actionClient);
        actionClient.setLayout(actionClientLayout);
        actionClientLayout.setHorizontalGroup(
            actionClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actionDetails2)
                .addContainerGap())
            .addGroup(actionClientLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(actionDescription2)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        actionClientLayout.setVerticalGroup(
            actionClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionClientLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(actionDescription2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(actionDetails2)
                .addContainerGap())
        );

        actionCaissier.setBackground(new java.awt.Color(250, 253, 255));
        actionCaissier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 206, 255), 1, true));
        actionCaissier.setForeground(new java.awt.Color(164, 206, 255));
        actionCaissier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actionCaissier.setPreferredSize(new java.awt.Dimension(180, 130));

        actionDescription3.setBackground(new java.awt.Color(255, 255, 255));
        actionDescription3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        actionDescription3.setForeground(new java.awt.Color(118, 130, 142));
        actionDescription3.setText("Caissiers");

        actionDetails3.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        actionDetails3.setForeground(new java.awt.Color(118, 130, 142));
        actionDetails3.setText("10 Caissiers");

        javax.swing.GroupLayout actionCaissierLayout = new javax.swing.GroupLayout(actionCaissier);
        actionCaissier.setLayout(actionCaissierLayout);
        actionCaissierLayout.setHorizontalGroup(
            actionCaissierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionCaissierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actionDetails3)
                .addContainerGap())
            .addGroup(actionCaissierLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(actionDescription3)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        actionCaissierLayout.setVerticalGroup(
            actionCaissierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionCaissierLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(actionDescription3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(actionDetails3)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainActionContainerLayout = new javax.swing.GroupLayout(mainActionContainer);
        mainActionContainer.setLayout(mainActionContainerLayout);
        mainActionContainerLayout.setHorizontalGroup(
            mainActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainActionContainerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(mainActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainActionContainerLayout.createSequentialGroup()
                        .addComponent(actionVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(actionVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainActionContainerLayout.createSequentialGroup()
                        .addComponent(actionClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(actionCaissier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        mainActionContainerLayout.setVerticalGroup(
            mainActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainActionContainerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(mainActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(mainActionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionCaissier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchVehiculeLabel)
                    .addGroup(mainContainerLayout.createSequentialGroup()
                        .addComponent(searchVehiculeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(searchVehiculeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(makeResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(addVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(separator3)
                    .addComponent(mainActionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(searchVehiculeLabel)
                .addGap(6, 6, 6)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchVehiculeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchVehiculeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(makeResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mainActionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        searchVehiculeField.getAccessibleContext().setAccessibleName("Rechercher un vehicule");

        menuFichier.setText("Fichier");
        menuFichier.setToolTipText("");

        jMenuItem1.setText("jMenuItem1");
        menuFichier.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        menuFichier.add(jMenuItem2);
        menuFichier.add(jSeparator1);

        actionQuitter.setText("Quitter");
        actionQuitter.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                actionQuitterMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        actionQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actionQuitterMousePressed(evt);
            }
        });
        actionQuitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                actionQuitterKeyPressed(evt);
            }
        });
        menuFichier.add(actionQuitter);

        MenuBar.add(menuFichier);

        menuEdition.setText("Edition");
        MenuBar.add(menuEdition);

        menuAide.setText("?");

        jMenuItem4.setText("A propos");
        menuAide.add(jMenuItem4);

        MenuBar.add(menuAide);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(statusContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(statusContainer, 55, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigationContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        navigationContainer.getAccessibleContext().setAccessibleName("Menu de navigation");
        navigationContainer.getAccessibleContext().setAccessibleDescription("Menu de navigation vers les principales fonctionnalités de parkoo");

        getAccessibleContext().setAccessibleDescription("Parkoo cars inventory managment system build by Wlabs.");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //TODO: Fix this, to work properly & imageIcon URL Bug    
    JPanel[] allSpans;
    JPanel[] allLinks;


    private void linkHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkHomeMousePressed
        // TODO add your handling code here:
        setColor(linkHome);
        span1.setOpaque(true);
        resetColor(allLinks, allSpans, linkHome, span1);
    }//GEN-LAST:event_linkHomeMousePressed

    private void linkVoitureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkVoitureMousePressed
        // TODO add your handling code here:
        setColor(linkVoiture);
        span2.setOpaque(true);
        resetColor(allLinks, allSpans, linkVoiture, span2);
    }//GEN-LAST:event_linkVoitureMousePressed

    private void linkVenteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkVenteMousePressed
        // TODO add your handling code here:
        setColor(linkVente);
        span3.setOpaque(true);
        resetColor(allLinks, allSpans, linkVente, span3);
    }//GEN-LAST:event_linkVenteMousePressed

    private void linkClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkClientMousePressed
        // TODO add your handling code here:
        setColor(linkClient);
        span4.setOpaque(true);
        resetColor(allLinks, allSpans, linkClient, span4);
    }//GEN-LAST:event_linkClientMousePressed

    private void linkCaissierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkCaissierMousePressed
        // TODO add your handling code here:
        setColor(linkCaissier);
        span5.setOpaque(true);
        resetColor(allLinks, allSpans, linkCaissier, span5);
    }//GEN-LAST:event_linkCaissierMousePressed

    private void actionQuitterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionQuitterMousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_actionQuitterMousePressed

    private void actionQuitterMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_actionQuitterMenuKeyPressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_actionQuitterMenuKeyPressed

    private void actionQuitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_actionQuitterKeyPressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_actionQuitterKeyPressed

    private void searchVehiculeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVehiculeButtonActionPerformed
        // TODO add your handling code here:
        Voiture searchVehiculeResult = findVoitureById(searchVehiculeField.getText());
    }//GEN-LAST:event_searchVehiculeButtonActionPerformed

    private void addVehiculeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehiculeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehiculeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    /* All methods */
    //Method setColor
    private void setColor(JPanel panel) {
        panel.setBackground(new Color(79, 134, 214));
    }

    //Method resetColor
    private void resetColor(JPanel[] panels, JPanel[] indicators, JPanel currentPanel, JPanel currentIndicator) {
        for (JPanel panel : panels) {
            if (panel.equals(currentPanel)) {
                continue;
            }
            panel.setBackground(new Color(61, 118, 202));
        }
        for (JPanel indicator : indicators) {
            if (indicator.equals(currentIndicator)) {
                continue;
            }
            indicator.setOpaque(false);
        }
    }

    //Method switchPanel
    private void switchPanel(JPanel currentPanel, JPanel targetPanel) {
        currentPanel.setVisible(false);
        targetPanel.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel actionCaissier;
    private javax.swing.JPanel actionClient;
    private javax.swing.JLabel actionDescription;
    private javax.swing.JLabel actionDescription1;
    private javax.swing.JLabel actionDescription2;
    private javax.swing.JLabel actionDescription3;
    private javax.swing.JLabel actionDetails;
    private javax.swing.JLabel actionDetails1;
    private javax.swing.JLabel actionDetails2;
    private javax.swing.JLabel actionDetails3;
    private javax.swing.JMenuItem actionQuitter;
    private javax.swing.JPanel actionVente;
    private javax.swing.JPanel actionVoiture;
    private javax.swing.JLabel actualPanel;
    private javax.swing.JButton addVehicule;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel linkCaissier;
    private javax.swing.JLabel linkCaissierText;
    private javax.swing.JPanel linkClient;
    private javax.swing.JLabel linkClientText;
    private javax.swing.JPanel linkHome;
    private javax.swing.JLabel linkHomeText;
    private javax.swing.JPanel linkVente;
    private javax.swing.JLabel linkVenteText;
    private javax.swing.JPanel linkVoiture;
    private javax.swing.JLabel linkVoitureText;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainActionContainer;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JButton makeResult;
    private javax.swing.JMenu menuAide;
    private javax.swing.JMenu menuEdition;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JPanel navigationContainer;
    private javax.swing.JButton searchVehiculeButton;
    private javax.swing.JTextField searchVehiculeField;
    private javax.swing.JLabel searchVehiculeLabel;
    private javax.swing.JPanel separator;
    private javax.swing.JPanel separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JPanel span1;
    private javax.swing.JPanel span2;
    private javax.swing.JPanel span3;
    private javax.swing.JPanel span4;
    private javax.swing.JPanel span5;
    private javax.swing.JPanel statusContainer;
    // End of variables declaration//GEN-END:variables
}
